from __future__ import annotations

import argparse
import shutil
import subprocess
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FIG_DIR = REPO / "figures"
OUT_PDF = FIG_DIR / "architecture.pdf"
TEX_NAME = "architecture.tex"
ENGINES = ("pdflatex", "lualatex")

_TEX_SOURCE = r"""% Ultra-CAN architecture diagram (multi-task heads).
% Generated by ultra-can/scripts/make_fig_architecture.py -- edit
% that script (not this file) and re-run it.
\documentclass[border=2pt,10pt]{standalone}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{newtxtext}
\usepackage{newtxmath}
\usepackage{tikz}
\usetikzlibrary{arrows.meta}

% ------------------------------------------------------------- palette ------
\definecolor{sharedEdge}{HTML}{2F6DB3}
\definecolor{sharedFill}{HTML}{E9F2FA}
\definecolor{aggEdge}{HTML}{5A5A5A}
\definecolor{commEdge}{HTML}{3F7D4A}
\definecolor{commFill}{HTML}{EAF5EB}
\definecolor{sensEdge}{HTML}{BF5B12}
\definecolor{sensFill}{HTML}{FCEFE4}
\definecolor{coreEdge}{HTML}{8A6D00}
\definecolor{coreFill}{HTML}{FFF6D5}
\definecolor{flowCol}{HTML}{262626}
\definecolor{noteCol}{HTML}{767676}

\tikzset{
  flow/.style      = {draw=flowCol, line width=1.0pt},
  flowarrow/.style = {flow, -{Latex[length=1.9mm,width=1.5mm]}},
  refarrow/.style  = {draw=sharedEdge, dashed, line width=0.7pt,
                      -{Latex[length=1.6mm,width=1.2mm]}},
  auxarrow/.style  = {draw=noteCol, densely dotted, line width=0.65pt,
                      -{Latex[length=1.5mm,width=1.1mm]}},
  blk/.style       = {draw, rounded corners=2.5pt, line width=0.8pt},
  grpShared/.style = {draw=sharedEdge, dashed, line width=0.7pt,
                      rounded corners=3pt, fill=sharedFill!40},
  grpAgg/.style    = {draw=aggEdge, dashed, line width=0.7pt,
                      rounded corners=3pt, fill=black!3},
  grpHead/.style   = {draw=aggEdge, dashed, line width=0.7pt,
                      rounded corners=3pt, fill=white},
  gtitle/.style    = {font=\footnotesize\bfseries, text=black!85},
  gsub/.style      = {font=\scriptsize, text=black!55},
  dim/.style       = {font=\scriptsize, text=black!75, inner sep=1pt},
  bus/.style       = {font=\footnotesize, text=black!70, fill=white,
                      inner sep=1pt},
  notetxt/.style   = {font=\scriptsize\itshape, text=noteCol},
  core/.style      = {circle, draw=coreEdge, line width=1.1pt, fill=coreFill,
                      inner sep=0pt, minimum size=1.40cm},
}

\begin{document}
\begin{tikzpicture}[font=\footnotesize, align=center]

% -------------------------------------------------------- macro-areas -------
\draw[grpShared] (0.25,1.95) rectangle (3.65,8.85);
\draw[grpShared] (3.95,1.95) rectangle (8.25,8.85);
\draw[grpAgg]    (8.55,1.95) rectangle (14.15,8.85);
\draw[grpHead]   (14.45,1.95) rectangle (18.55,8.85);

\node[gtitle,text=sharedEdge] at (1.95,8.55) {Input};
\node[gsub] at (1.95,8.22) {communication stream only};

\node[gtitle,text=sharedEdge] at (6.10,8.55) {Shared Feature Extractor};
\node[gsub] at (6.10,8.22) {$K{=}3$, same padding, ReLU};

\node[gtitle,text=aggEdge] at (11.35,8.55) {Aggregation Variants};
\node[gsub] at (11.35,8.22)
  {one active at a time $\cdot$ $\mathbf{v}\in\mathbb{R}^{64}$};

\node[gtitle,text=aggEdge] at (16.50,8.55) {Multi-Task Heads};
\node[gsub] at (16.50,8.22) {independent heads on shared $\mathbf{v}$};

% --------------------------------------- side-information buses (lower) -----
\draw[auxarrow] (7.325,4.30) -- (7.325,1.60) -- (15.90,1.60) -- (15.90,2.25);
\draw[refarrow] (3.20,0.90) -- (16.60,0.90) -- (16.60,2.25);
\node[bus] at (11.20,1.60)
  {$\mathbf{p}\in\mathbb{R}^{64}$: positional feature (0 parameters)};
\node[bus] at (11.60,0.90)
  {delay profile $\rho\in\mathbb{R}^{99}$ (matched filter)};

% ---------------------------------------------------------------- input -----
\node[notetxt] at (1.95,7.45) {the shared backbone\\never sees $x[n]$};
\node[blk, draw=sharedEdge, fill=sharedFill, minimum width=2.6cm,
      minimum height=2.6cm] (ybox) at (1.95,5.10)
  {\textbf{Received I/Q burst}\\[1pt]
   complex baseband\\[3pt]
   {\small$\mathbf{Y}\in\mathbb{R}^{100\times 2}$}};
\node[blk, draw=sharedEdge!80!black, fill=sharedFill!60, minimum width=2.5cm,
      minimum height=1.4cm] (refbox) at (1.95,0.90)
  {\textbf{Chaotic reference}\\[1pt]
   $x[n]\in\mathbb{R}^{100}$\\[1pt]
   {\itshape locally regenerated}};

% ------------------------------------------- shared feature extractor -------
\node[blk, draw=sharedEdge, fill=sharedFill, minimum width=1.45cm,
      minimum height=1.6cm] (c1) at (4.875,5.10)
  {\textbf{Conv1D}\\[1pt] $F_1{=}32$\\[1pt] $K{=}3$};
\node[blk, draw=sharedEdge, fill=sharedFill, minimum width=1.45cm,
      minimum height=1.6cm] (c2) at (7.325,5.10)
  {\textbf{Conv1D}\\[1pt] $F_2{=}64$\\[1pt] $K{=}3$};

\draw[flowarrow] (ybox.east) -- (c1.west);
\draw[flowarrow] (c1.east) -- node[dim,above=1pt] {ReLU} (c2.west);
\draw[flow] (c2.east) -- (9.00,5.10);

% -------------------------------------------------- aggregation variants ----
\fill[flowCol] (9.00,5.10) circle (1.1pt);
\draw[flow] (9.00,3.35) -- (9.00,6.85);
\draw[flowarrow] (9.00,6.85) -- (9.825,6.85);
\draw[flowarrow] (9.00,3.35) -- (9.825,3.35);
\node[dim] at (9.95,5.10) {$H^{\mathrm{att}}\in\mathbb{R}^{100\times 64}$};

\node[blk, draw=aggEdge, fill=black!6, minimum width=2.85cm,
      minimum height=1.8cm] (att) at (11.25,6.85)
  {\textbf{Attention Pooling}\\[1pt]
   (Ultra-CAN)\\[1pt]
   temporal softmax $\alpha_i$\\[1pt]
   $\mathbf{v}=\sum_i \alpha_i\,\mathbf{h}[i]$};
\node[blk, draw=aggEdge, fill=black!6, minimum width=2.85cm,
      minimum height=1.8cm] (qkv) at (11.25,3.35)
  {\textbf{QKV Attention}\\[1pt]
   (Ultra-CAN-QKV)\\[1pt]
   $H{=}8$, $d_k{=}8$, sinus.~PE\\[1pt]
   residual, GAP $\to$ $\mathbb{R}^{64}$};

% ----------------------------------- shared representation (the interface) --
\node[core] (vnode) at (13.30,5.10) {{\small$\mathbf{v}$}\\[1pt]
  $\in\mathbb{R}^{64}$};
\draw[flowarrow] (att.east) -- (vnode);
\draw[flowarrow] (qkv.east) -- (vnode);
\draw[flow] (vnode.east) -- (14.60,5.10);

% ------------------------------------------------------ read-out --
\fill[flowCol] (14.60,5.10) circle (1.1pt);
\draw[flowarrow] (14.60,5.10) -- (14.60,7.05) -- (15.45,7.05);
\draw[flowarrow] (14.60,5.10) -- (14.60,3.15) -- (15.45,3.15);
\node[dim] at (15.02,7.30) {$\mathbb{R}^{64}$};
\node[dim] at (15.02,2.90) {$\mathbb{R}^{64}$};

\node[blk, draw=commEdge, fill=commFill, minimum width=2.9cm,
      minimum height=1.8cm] (comm) at (16.90,7.05)
  {\textbf{Communication Head}\\[1pt]
   Dropout $p{=}0.3$\\[1pt]
   Dense(128), ReLU\\[1pt]
   logits $\hat{\mathbf{b}}$, 8{,}578 parameters};
\node[blk, draw=sensEdge, fill=sensFill, minimum width=2.9cm,
      minimum height=1.8cm] (sens) at (16.90,3.15)
  {\textbf{Sensing Head}\\[1pt]
   $[\mathbf{v};\mathbf{p};\rho]\in\mathbb{R}^{227}$\\[1pt]
   Dense(32), ReLU\\[1pt]
   $\hat{\tau}$ (delay), $f_D$ aux.};

\draw[flowarrow] (comm.east) -- (18.80,7.05);
\node[font=\small] at (19.00,7.05) {$\hat{b}$};
\draw[flowarrow] (sens.east) -- (18.80,3.15);
\node[font=\small] at (19.00,3.15) {$\hat{\tau}$};

\end{tikzpicture}
\end{document}
"""

def _latex_engine() -> str:
    for name in ENGINES:
        if shutil.which(name):
            return name
    raise SystemExit(
        "[error] no LaTeX engine found (looked for: "
        + ", ".join(ENGINES)
        + ").\n"
        "        The architecture diagram is drawn in TikZ, so a TeX\n"
        "        distribution with standalone/tikz/newtx is required, e.g.\n"
        "        'sudo apt install texlive-latex-extra texlive-pictures "
        "texlive-fonts-extra'."
    )

def _compile(engine: str, workdir: Path) -> Path:
    (workdir / TEX_NAME).write_text(_TEX_SOURCE, encoding="utf-8")
    cmd = [engine, "-interaction=nonstopmode", "-halt-on-error",
           "-file-line-error", TEX_NAME]
    for _ in range(2):
        proc = subprocess.run(
            cmd, cwd=workdir, stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT, text=True,
        )
        if proc.returncode != 0:
            log = workdir / f"{TEX_NAME[:-4]}.log"
            detail = (log.read_text(errors="ignore")
                      if log.exists() else proc.stdout)
            raise SystemExit(
                f"[error] {engine} failed on {TEX_NAME}:\n{detail[-3000:]}"
            )
    pdf = workdir / f"{TEX_NAME[:-4]}.pdf"
    if not pdf.is_file():
        raise SystemExit(f"[error] {engine} produced no PDF for {TEX_NAME}")
    return pdf

def _mirror() -> None:
    mirror_dir = REPO / "results" / "figures"
    if mirror_dir.is_dir():
        shutil.copyfile(OUT_PDF, mirror_dir / OUT_PDF.name)
        print("saved", mirror_dir / OUT_PDF.name)

def render(keep_tex: bool = False) -> None:
    engine = _latex_engine()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="arch_tikz_") as tmp:
        workdir = Path(tmp)
        pdf = _compile(engine, workdir)
        shutil.copyfile(pdf, OUT_PDF)
        print("saved", OUT_PDF)
        if keep_tex:
            shutil.copyfile(workdir / TEX_NAME, FIG_DIR / TEX_NAME)
            print("saved", FIG_DIR / TEX_NAME)
    _mirror()

def main(argv=None) -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--keep-tex", action="store_true",
                    help="also write figures/architecture.tex")
    args = ap.parse_args(argv)
    render(keep_tex=args.keep_tex)

if __name__ == "__main__":
    main()
